# Generated by Django 2.1.4 on 2018-12-24 11:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PxBugCount',
            fields=[
                ('bugid', models.AutoField(primary_key=True, serialize=False, verbose_name='BUGid')),
                ('bug_pvid', models.CharField(max_length=100, verbose_name='BUG大版本数据ID')),
                ('bug_pmid', models.CharField(max_length=100, verbose_name='BUG提测版本编号')),
                ('bug_zj', models.CharField(default=0, max_length=100, verbose_name='BUG组件模块ID')),
                ('bug_wtms', models.CharField(max_length=100, verbose_name='BUG问题描述')),
                ('bug_cdbh', models.CharField(max_length=100, verbose_name='BUG禅道编号')),
                ('bug_sfxmk', models.CharField(max_length=10, verbose_name='BUG是否新模块')),
                ('bug_wtdj', models.CharField(max_length=10, verbose_name='BUG问题等级')),
                ('bug_xgyxj', models.CharField(max_length=10, verbose_name='BUG修改优先级')),
                ('bug_sfyjj', models.CharField(max_length=10, verbose_name='BUG是否已解决')),
                ('bug_sfyztg', models.CharField(max_length=10, verbose_name='BUG是否验证通过')),
                ('bug_sfhg', models.CharField(max_length=10, verbose_name='BUG是否为回归')),
                ('bug_cjr', models.CharField(max_length=10, verbose_name='BUG添加人')),
                ('bug_tjsj', models.DateTimeField(default=django.utils.timezone.now, verbose_name='BUG添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='PxModular',
            fields=[
                ('pmid', models.AutoField(primary_key=True, serialize=False, verbose_name='组件模块ID')),
                ('pmtype', models.BooleanField(default=True, verbose_name='组件类型')),
                ('pmname', models.CharField(max_length=30, verbose_name='组件模块名称')),
                ('datatime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
            ],
        ),
        migrations.CreateModel(
            name='PxVersion',
            fields=[
                ('pvid', models.AutoField(primary_key=True, serialize=False, verbose_name='版本数据ID')),
                ('pvname', models.CharField(max_length=100, verbose_name='交付版本名称')),
                ('pvnumber', models.CharField(max_length=100, verbose_name='提测版本编号')),
                ('datatime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
            ],
        ),
        migrations.CreateModel(
            name='ShuJuCount',
            fields=[
                ('typeid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('type_data', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
                ('datatime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
            ],
        ),
    ]
