# Generated by Django 2.1.4 on 2018-12-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pxbugcount',
            name='bug_zj',
            field=models.CharField(max_length=100, verbose_name='BUG组件模块ID'),
        ),
    ]
