# Generated by Django 2.1.4 on 2019-01-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_manage', '0002_auto_20181224_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pxbugcount',
            name='bug_wtms',
            field=models.CharField(max_length=255, verbose_name='BUG问题描述'),
        ),
    ]
