# Generated by Django 2.1.4 on 2019-02-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_manage', '0005_saveimage_bug_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default=12, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32),
        ),
        migrations.AlterField(
            model_name='saveimage',
            name='img_url',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
